### ISSUE TITLE
Missing sidebar navigation hook

### ISSUE THREAD

**Issue by flippidippi** [WheelhouseCMS/wheelhouse-page-fragments#1]
Since this plugin overwrites the `_navigation_options.html.haml` file can it also contain the navigation options hook? Would the hook still work if it's define in a plugin like that? We need to add a new field below path.

```ruby
= resource_hook(:"sidebar.navigation_options")`
```

**Comment by spohlenz** [comment]
Thank you. That was indeed an oversight.
