### ISSUE TITLE
Not precompiling image

### ISSUE THREAD

**Issue by flippidippi** [WheelhouseCMS/wheelhouse-page-fragments#2]
We have to add the following for the plugin to work

```
Rails.application.config.assets.precompile += %w( page-fragments/fragment.png )
```

Can this be added to the plugin's `config.precompile` please?

**Comment by spohlenz** [comment]
Thank you. This behaviour was changed in Sprockets somewhere along the way but has now been updated. Please let me know if there are any other plugins you are using that need updating.
